Failure # 1 (occurred at 2025-05-22_21-57-45)
[36mray::ImplicitFunc.train()[39m (pid=84466, ip=127.0.0.1, actor_id=9e7e8b5307fdf1f2ea60120201000000, repr=lstm_objective)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.13/site-packages/ray/tune/trainable/trainable.py", line 330, in train
    raise skipped from exception_cause(skipped)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.13/site-packages/ray/air/_internal/util.py", line 107, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.13/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.13/site-packages/ray/tune/trainable/function_trainable.py", line 261, in _trainable_func
    output = fn()
  File "/Users/mikeedwards/Library/Mobile Documents/com~apple~CloudDocs/pMike/Unity/price/training/objectives.py", line 17, in lstm_objective
    train_loader, val_loader = build_dataloaders(batch=64)
                               ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/mikeedwards/Library/Mobile Documents/com~apple~CloudDocs/pMike/Unity/price/training/datamodule.py", line 25, in build_dataloaders
    train = PriceDataset("data/pre_train.parquet")
  File "/Users/mikeedwards/Library/Mobile Documents/com~apple~CloudDocs/pMike/Unity/price/training/datamodule.py", line 6, in __init__
    df = pd.read_parquet(parquet_path)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.13/site-packages/pandas/io/parquet.py", line 667, in read_parquet
    return impl.read(
           ~~~~~~~~~^
        path,
        ^^^^^
    ...<6 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.13/site-packages/pandas/io/parquet.py", line 267, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ~~~~~~~~~~~~~~~~~~~^
        path,
        ^^^^^
    ...<2 lines>...
        mode="rb",
        ^^^^^^^^^^
    )
    ^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.13/site-packages/pandas/io/parquet.py", line 140, in _get_path_or_handle
    handles = get_handle(
        path_or_handle, mode, is_text=False, storage_options=storage_options
    )
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.13/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/pre_train.parquet'
